### ISSUE TITLE
Improve the card design 

### ISSUE THREAD

**Issue by shriya-tiwari** [shriya-tiwari/Reciplay_website#3]
The card design displayed is very simple, looking forward to some enhancemenst in it.

**Comment by robin6717** [comment]
Hi, can I give that a try? I would love that!

kind regards,

Robin

**Comment by shriya-tiwari** [comment]
yup go ahead

**Comment by robin6717** [comment]
Hi,
thank you. The api does not provide me with cards/recipees. Any idea why? I will look into this later but maybe you can give me a hint..( nothing happens when I submit the ingredients )

**Comment by robin6717** [comment]
Maybe this is too difficult for me yet.. I kind of like your design of the cards already.. Can you please unasign me? Im sry to have bothered you. Next time i wll try first before asking to assign me.

**Comment by shriya-tiwari** [comment]
are you entering the ingredients on the cuisine page, because it wont work there, it can work only for the home page.

**Comment by robin6717** [comment]
yes, i try it on the home page

**Comment by robin6717** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at HTMLButtonElement.addingredient (index.js:41:20)
addingredient @ index.js:41
index.js:105 Uncaught TypeError: Cannot read properties of undefined (reading 'join')
    at refresh (index.js:105:29)
    at HTMLButtonElement.onclick (home.html:49:118)

**Comment by shriya-tiwari** [comment]
You dont need to change anything with the logic, only css and html of the cards, if you still dont want to try, then i will unassign, no problem.

**Comment by shriya-tiwari** [comment]
> Uncaught TypeError: Cannot read properties of undefined (reading 'push') at HTMLButtonElement.addingredient (index.js:41:20) addingredient @ index.js:41 index.js:105 Uncaught TypeError: Cannot read properties of undefined (reading 'join') at refresh (index.js:105:29) at HTMLButtonElement.onclick (home.html:49:118)

Hmmm, this should not happen unless you have made any changes to the code of index.js file.

**Comment by robin6717** [comment]
I understand, yes please unassign..  I really like the project tho! It is a great idea and looks great...If i manage to make something may I then send you a screenshot to show it? thank you for your understanding.

**Comment by robin6717** [comment]
also the pop method did not work btw..
Uncaught TypeError: Cannot read properties of undefined (reading 'pop')
    at list.onclick (index.js:31:24)

**Comment by shriya-tiwari** [comment]
> I understand, yes please unassign.. I really like the project tho! It is a great idea and looks great...If i manage to make something may I then send you a screenshot to show it? thank you for your understanding.

No problem, i will unassign you. But if you figure out something be sure to come back and make contributions. This is what open source is about, helping and learning from each other :)

**Comment by shriya-tiwari** [comment]
> also the pop method did not work btw.. Uncaught TypeError: Cannot read properties of undefined (reading 'pop') at list.onclick (index.js:31:24)

I think its happening because the api key is not available. I will do that now.

**Comment by shriya-tiwari** [comment]
You can again fork the repository and try it if you want, it should work this time.

**Comment by robin6717** [comment]
ok I will do that now!

**Comment by robin6717** [comment]
if you can wait max 2 days  to wait for the result I would like to stay assigned !

**Comment by robin6717** [comment]
![screen](https://user-images.githubusercontent.com/97845123/197161175-d0f3d0a1-fc72-4701-8cf7-c4e8a46cbc40.png)

**Comment by dasashreeya** [comment]
Hey can I work on this issue if it is still open?

**Comment by shriya-tiwari** [comment]
@robin6717  i cant see many changes in the design of the card, except for the color change. If you can make any more prominent changes, it would be better.

**Comment by shriya-tiwari** [comment]
Yes you can go ahead @dasashreeya 👍

**Comment by dasashreeya** [comment]
Hey, do you want me to make a carousel-type design where you can click on arrows to see the next recipe card?

**Comment by shriya-tiwari** [comment]
> Hey, do you want me to make a carousel-type design where you can click on arrows to see the next recipe card?

Yes that would be really good, if you can do it please go ahead.

**Comment by dasashreeya** [comment]
Hey can you assign it to someone else? I tried it and I can’t seem to work
with APIs

**Comment by shriya-tiwari** [comment]
Ok no problem, can you share what problem you were facing?
